version: '3'

services:
  application.api:
    image: application.api
    build:
      context: ./Application.API
      dockerfile: Dockerfile
    depends_on: 
      - db
  db:
    image: "microsoft/mssql-server-windows-express"
    environment:
        sa_password: "sql_SA_pwd"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"